### PR TITLE
Update and verify directions for getting running on M1.

### PR DESCRIPTION
**Pull request by vaikas**
@danpopnyc 

Ok, went through and verified with a clean install.

Signed-off-by: Ville Aikas <vaikas@chainguard.dev>

### CODE REVIEW

**Comment by danpopnyc** [comment]
seeing an issue with the mysql image
Screen Shot 2022-01-25 at 1 20 23 PM

**Comment by danpopnyc** [comment]
machine is running no issues after running new steps! :)

**Comment by vaikas** [comment]
Woot Woot, and just to double-check, the error with mysql not coming up was running with release.yaml vs. release-arm.yaml?

**Comment by danpopnyc** [comment]
correct.  runs perfectly after changing to release-arm.yaml
Screen Shot 2022-01-25 at 1 39 58 PM

**Comment by danpopnyc** [comment]
Visual confirmation Screen Shot 2022-01-25 at 1 41 35 PM

**Pull request merged**
